wandb_version: 1

act_fn:
  value: relu
attention_dir:
  value: causal
attn_only:
  value: false
batch_size:
  value: 512
d_head:
  value: 32
d_mlp:
  value: 64
d_model:
  value: 256
d_vocab:
  value: 2
init_weights:
  value: true
learning_rate:
  value: 1.0e-06
n_ctx:
  value: 10
n_heads:
  value: 2
n_layers:
  value: 8
normalization_type:
  value: null
num_epochs:
  value: 200
optimizer:
  value: sgd
seed:
  value: 42
use_attn_scale:
  value: true
weight_decay:
  value: 0.02
