wandb_version: 1

act_fn:
  value: relu
attention_dir:
  value: causal
attn_only:
  value: false
batch_size:
  value: 8192
d_head:
  value: 4
d_mlp:
  value: 64
d_model:
  value: 128
d_vocab:
  value: 2
init_weights:
  value: true
learning_rate:
  value: 0.1
n_ctx:
  value: 10
n_heads:
  value: 1
n_layers:
  value: 32
normalization_type:
  value: LN
num_epochs:
  value: 10000
optimizer:
  value: sgd
seed:
  value: 42
use_attn_scale:
  value: true
weight_decay:
  value: 0.04
