wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705635379.743216
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 2
      - 23
      - 37
      4: 3.11.7
      5: 0.16.1
      6: 4.36.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
