wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705623370.409489
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.11.7
      5: 0.16.1
      6: 4.36.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
