global_config:
  output_dir: "./results"
  device: cuda
  parallel: true
  wandb: true
  wandb_project: "quantum_transformer"
  process_dir: "./process_data"
  val_every: 1 # after n epochs, ~ is None
  scheduler: true
  save_every: 100

train_config:
  batches_per_epoch: 200
  bos: false
  n_epochs: 20000

model_config:
  n_ctx: 8
  act_fn: "relu"
  normalization_type: "LN"
  attn_only: false
  seed: 42
  dtype: float32

sweep_config:
  train_config:
    learning_rate:
      - 1.0e-4
    batch_size:
      - 128
  model_config:
    d_head:
      - 16
    n_layers:
      - 2
    n_heads:
      - 2
  process_config:
    - name: "tom_quantum"
      alpha: 1.0
      beta: 7.14142842854285
    - name: "mess3"
      x: 0.05
      a: 0.85