wandb_version: 1

act_fn:
  desc: null
  value: relu
attention_dir:
  desc: null
  value: causal
attn_only:
  desc: null
  value: false
batch_size:
  desc: null
  value: 128
d_head:
  desc: null
  value: 4
d_mlp:
  desc: null
  value: 256
d_model:
  desc: null
  value: 8
d_vocab:
  desc: null
  value: 2
init_weights:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.01
n_ctx:
  desc: null
  value: 10
n_heads:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 8
normalization_type:
  desc: null
  value: null
num_epochs:
  desc: null
  value: 1000
optimizer:
  desc: null
  value: adam
seed:
  desc: null
  value: 42
use_attn_scale:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.09
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706588798.116289
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 2
      - 23
      - 37
      4: 3.11.7
      5: 0.16.1
      6: 4.36.2
      8:
      - 4
      - 5
      13: darwin-arm64
